# Generated by Django 5.2.4 on 2025-08-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Descrição', models.TextField(blank=True, null=True)),
                ('Categoria', models.CharField(choices=[('1', 'Educação'), ('2', 'Água'), ('3', 'Luz'), ('4', 'Aluguel'), ('5', 'Comida'), ('6', 'Lazer'), ('7', 'Drogas'), ('8', 'Outros')], max_length=1)),
                ('Data', models.DateField()),
            ],
        ),
    ]
